wandb_version: 1

max_epochs:
  desc: null
  value: 3000
early_stopping_patience:
  desc: null
  value: 50
save_every:
  desc: null
  value: 5
seed:
  desc: null
  value: 42
model_name:
  desc: null
  value: Sequential
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1695631988.053254
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.11
      8:
      - 2
      - 5
      13: linux-x86_64
